config/routes.rb
Rails.application.routes.draw do
  
  # 顧客用
  # URL /customers/sign_in...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  namespace :public do
    root to: "homes#top"
    get "/about" => "homes#about", as: "about"
    post "/orders/confirm" => "orders#confirm"
    get "/orders/finish" => "orders#finish"
    resources :orders, only: [:new, :create, :index, :show]
    resources :items, only: [:index, :show]
    # resources :customers, only: [:show, :edit, :update]
    get "/customers/show" => "customers#show"
    get "/customers/show/eidt" => "customers#edit"
    patch "/customers/show" => "customers#update"
    get "/customers/check" => "customers#check"
    patch "/customers/withdraw" => "customers#withdraw"
    resources :cart_items, only: [:index, :create, :update]
    delete "/cart_items/destroy_all" => "cart_items#destroy_all"
    delete "/cart_items/:id" => "cart_items#destroy"
  end
  
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    # root to: "homes#top"
    get "/homes" => "homes#top"
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show]
  end
  
  get "/about" => "homes#about", as: "about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :cart_items, dependent: :destroy
  has_many :order_items
  def get_image(width, height)
     unless image.attached?
       file_path = Rails.root.join('app/assets/images/no_image.jpg')
       image.attach(io: File.open(file_path), filename: 'default=image.jpg', content_type: 'image/jpeg')
     end
     image.variant(resize_to_limit: [width,height]).processed
  end
  
  def add_tax_price
    (self.price * 1.10).round
  end
  
  def with_tax_price
    (price * 1.1).floor
  end
    
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def new
    @item = Item.new
  end
  
  def index
    
    @items = Item.page(params[:page])
  end
  
  def show
    @item = Item.find(params[:id])
  end
  
  def create
    item = Item.new(item_params)
    item.save
    redirect_to admin_item_path(item.id)
  end
  
  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end
  
  private
  
    def item_params
      params.require(:item).permit(:name, :introduction, :image, :price)
    end
  
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container px-5 px-sm-0 py-5">
  <div class="row">
    <h1>商品編集画面</h1>
  </div>
  
  <%= form_with model: @item, url: admin_item_path(@item.id), method: :patch do |f| %>
  <div class="row py-5">
    <div class="col-md-9 offset-md-2">
      <table>
        <tr>
          <td><%= f.label :image, "商品画像" %></td>
          <td><%= f.file_field :image, accept: "image/*" %></td>
        </tr>
        <tr>
          <td><%= f.label :name, "商品名" %></td>
          <td><%= f.text_field :name, :size=>"50" %></td>
        </tr>
        <tr>
          <td><%= f.label :introduction, "商品説明" %></td>
          <td><%= f.text_area :introduction, :size=>"52x10" %></td>
        </tr>
        <tr>
          <td><%= f.label :price, "税抜価格" %></td>
          <td><%= f.text_field :price, :size=>"50" %>円</td>
        </tr>
      </table>
    </div>  
  </div>
  <div class="row">
    <div class="col-md-5 offset-md-5">
      <input class="btn btn-success" type="submit" value="変更を保存">
    </div>
  </div>
  <% end %>
</div>

app/views/admin/items/index.html.erb
<div class="container px-5 px-sm-0 py-5">
  <div class="row">
    <h1>商品一覧</h1>
    <div class="col-md-3 offset-md-7">
      <h2><%= link_to "+", new_admin_item_path %></h2>
    </div>  
  </div>
  <div class="row py-5">
    <div class="col-md-10">
      <table class="table">
        <thead class="table-light">
          <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
            <tr>
              <td>
                <%= item.id %>
              </td>
              <td>
                <%= link_to admin_item_path(item.id) do %>
                  <%= item.name %>
                <% end %>
              </td>
              <td>
                <%= item.price %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row justify-content-center">
    <%= paginate @items %>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container px-5 px-sm-0 py-5">
  <div class="row">
    <h1>商品新規登録</h1>
  </div>
  
  <%= form_with model:@item, url: admin_items_path do |f| %>
  <div class="row py-5">
    <div class="col-md-9 offset-md-2">
    <table>
      <tr>
        <td><%= f.label :image, "商品画像" %></td>
        <td><%= f.file_field :image, accept: "image/*" %></td>
      </tr>
      <tr>
        <td><%= f.label :name, "商品名" %></td>
        <td><%= f.text_field :name, :size=>"50" %></td>
      </tr>
      <tr>
        <td><%= f.label :introduction, "商品説明" %></td>
        <td><%= f.text_area :introduction, :size=>"52x10" %></td>
      </tr>
      <tr>
        <td><%= f.label :price, "税抜価格" %></td>
        <td><%= f.text_field :price, :size=>"50" %>円</td>
      </tr>
    </table>
    </div>
  </div>
  <div class="row">
    <div class="col-md-5 offset-md-5">
      <input class="btn btn-success" type="submit" value="新規登録">
    </div>
  </div>
</div>
<% end %>

app/views/admin/items/show.html.erb
<div class="container px-5 px-sm-0 py-5">
  <div class="row">
    <h1>商品詳細</h1>
  </div>

  <div class="row py-5">
    <div class="col-md-3">
      <%= image_tag @item.get_image(100,100), :size =>'200x200' %>
    </div>
    <table>
      <tr>
        <td>商品名</td>
        <td><%= @item.name %></td>
      </tr>
      <tr>
        <td>商品説明</td>
        <td><%= @item.introduction %></td>
      </tr>
      <tr>
        <td>税込価格<br>(税抜価格)　　</td>
        <td><%= @item.add_tax_price %>（<%= @item.price %>）円</td>
      </tr>
    </table>
  </div>
  <div class="row py-9">
    <div class="col-md-5 offset-md-4">
      <%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-sm btn-success" %>
    </div>  
  </div>
</div>