config/routes.rb
Rails.application.routes.draw do
  
  # 顧客用
  # URL /customers/sign_in...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  namespace :public do
    root to: "homes#top"
    get "/about" => "homes#about", as: "about"
    post "/orders/confirm" => "orders#confirm"
    get "/orders/finish" => "orders#finish"
    resources :orders, only: [:new, :create, :index, :show]
    resources :items, only: [:index, :show]
    # resources :customers, only: [:show, :edit, :update]
    get "/customers/show" => "customers#show"
    get "/customers/show/eidt" => "customers#edit"
    patch "/customers/show" => "customers#update"
    get "/customers/check" => "customers#check"
    patch "/customers/withdraw" => "customers#withdraw"
    resources :cart_items, only: [:index, :create, :update]
    delete "/cart_items/destroy_all" => "cart_items#destroy_all"
    delete "/cart_items/:id" => "cart_items#destroy"
  end
  
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    # root to: "homes#top"
    get "/homes" => "homes#top"
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show]
  end
  
  get "/about" => "homes#about", as: "about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items
  has_many :orders
  def full_name
    self.last_name + " " + self.first_name
  end
  
  def full_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end
  
  def customer_status
    if is_deleted == true
      "退会"
    else
      "有効"
    end
  end
  
  def active_for_authentication?
    super && (is_deleted == false)
  end
  
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @customers = Customer.all
  end
  
  def show 
    @customer = Customer.find(params[:id])
    
  end
  
  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path
  end
  
  private
  
    def customer_params
      params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
    end
    
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container px-5 px-sm-0 py-5">
  <div class="row">
    <h1><%= @customer.full_name %>さんの会員情報編集</h1>
  </div>
  <div class="row">
    <div class="col-md-10">
      <table cellpadding="15">
        <tbody>
          <%= form_with model: @customer, url: admin_customer_path(@customer.id), method: :patch do |f| %>
            <tr>
              <td>会員ID</td>
              <td><%= @customer.id %></td>
            </tr>
            <tr>
              <td>氏名</td>
              <td><%= f.text_field :last_name %></td>
              <td><%= f.text_field :first_name %></td>
            </tr>
            <tr>
              <td>フリガナ</td>
              <td><%= f.text_field :last_name_kana %></td>
              <td><%= f.text_field :first_name_kana %></td>
            </tr>
            <tr>
              <td>郵便番号</td>
              <td><%= f.text_field :postal_code %></td>
            </tr>
            <tr>
              <td>住所</td>
              <td>
                <%= f.text_field :address %>
              </td>
            </tr>
            <tr>
              <td>電話番号</td>
              <td><%= f.text_field :telephone_number %></td>
            </tr>
            <tr>
              <td>メールアドレス</td>
              <td>
                <%= f.email_field :email %>
              </td>
            </tr>
            <tr>
              <td>会員ステータス</td>
              <td>
                <%= f.radio_button :is_deleted, "true" %> 有効
                <%= f.radio_button :is_deleted, "false" %> 退会
              </td>
            </tr>
            <tr>
              <td></td>
              <td><input class="btn btn-success" type="submit" value="変更を保存"></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>  
  </div>    
</div>

app/views/admin/customers/index.html.erb
<div class="container px-5 px-sm-0 py-5">
  <div class="row">
    <h1>会員一覧</h1>
  </div>
  <div class="row py-5">
    <div class="col-md-10">
      <table class="table">
        <thead class="table-light">
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td>
              <%= link_to admin_customer_path(customer.id) do %>
                <%= customer.full_name %>
              <% end %>
            </td>
            <td><%= customer.email %></td>
            <td><%= customer.customer_status %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>  
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container px-5 px-sm-0 py-5">
  <div class="row">
    <h1><%= @customer.full_name %>さんの会員詳細</h1>
  </div>
  <div class="row">
    <div class="col-md-10">
      <table cellpadding="15">
        <div class="p-3">
        <tbody>
          <tr>
            <td>会員ID</td>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <td>氏名</td>
            <td><%= @customer.full_name %></td>
          </tr>
          <tr>
            <td>フリガナ</td>
            <td><%= @customer.full_name_kana %></td>
          </tr>
          <tr>
            <td>郵便番号</td>
            <td><%= @customer.postal_code %></td>
          </tr>
          <tr>
            <td>住所</td>
            <td><%= @customer.address %></td>
          </tr>
          <tr>
            <td>電話番号</td>
            <td><%= @customer.telephone_number %></td>
          </tr>
          <tr>
            <td>メールアドレス</td>
            <td><%= @customer.email %></td>
          </tr>
          <tr>
            <td>会員ステータス</td>
            <td style="color:green"><b><%= @customer.customer_status %></b></td>
          </tr>
        </tbody>
      </div>
      </table>
    </div>
  </div>
  <div class="row py-5">
    <div class="col-md-5 offset-md-2">
      <%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-sm btn-success" %>
      <%= link_to "注文履歴一覧を見る", admin_homes_path, class: "btn btn-sm btn-primary" %>
    </div>
  </div>
</div>