config/routes.rb
Rails.application.routes.draw do
  
  # 顧客用
  # URL /customers/sign_in...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  namespace :public do
    root to: "homes#top"
    get "/about" => "homes#about", as: "about"
    post "/orders/confirm" => "orders#confirm"
    get "/orders/finish" => "orders#finish"
    resources :orders, only: [:new, :create, :index, :show]
    resources :items, only: [:index, :show]
    # resources :customers, only: [:show, :edit, :update]
    get "/customers/show" => "customers#show"
    get "/customers/show/eidt" => "customers#edit"
    patch "/customers/show" => "customers#update"
    get "/customers/check" => "customers#check"
    patch "/customers/withdraw" => "customers#withdraw"
    resources :cart_items, only: [:index, :create, :update]
    delete "/cart_items/destroy_all" => "cart_items#destroy_all"
    delete "/cart_items/:id" => "cart_items#destroy"
  end
  
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    # root to: "homes#top"
    get "/homes" => "homes#top"
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show]
  end
  
  get "/about" => "homes#about", as: "about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  belongs_to :customer
  enum payment_method: { credit_card: 0, transfer: 1 }
  
  def address_display
  '〒' + current_customer.postal_code + ' ' + current_customer.address + ' ' + current_customer.last_name + ' ' + current_customer.first_name
  end
  
  SIPPING_COST = 800
  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  def show
    @order = Order.find(params[:id])
    @customer = @order.customer
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container px-5 px-sm-0 py-5">
  <div class="row">
    <h1>注文履歴詳細</h1>
  </div>
  <div class="row py-3">
    <div class="col-md-6">
      <table cellpadding="10">
        <tr>
          <td><b>購入者</b></td>
          <td>
            <%= link_to admin_customer_path(@customer.id) do %>
              <%= @order.name %>
            <% end %>
          </td>
        </tr>
        <tr>
          <td><b>注文日</b></td>
          <td><%= @order.updated_at.strftime('%Y/%m/%d') %></td>
        </tr>
        <tr>
          <td><b>配送先</b></td>
          <td>〒<%= @order.postal_code%>
              <%= @order.address %><br>
              <%= @order.name %></td>
        </tr>
        <tr>
          <td><b>支払方法</b></td>
          <td><%= @order.payment_method_i18n %></td>
        </tr>
      </table>
    </div>
  </div>
  
  <div class="row py-3">
    <div class="col-md-9 py-5">
      <table class="table table-bordered border-dark">
        <thead bgcolor="#f5f5f5">
          <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
          </tr>
        </thead>
        <% @order.order_items.each do |order_item| %>
        <tbody>
          <tr>
            <td><%= order_item.item.name %></td>
            <td><%= (order_item.tax_price * 1.1).floor %></td>
            <td><%= order_item.item_amount %></td>
            <td><%= (order_item.tax_price * 1.1).floor * order_item.item_amount %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
    <div class="col-md-3 py-5">
      <table cellpadding="10">
        <tr>
          <td><b>商品合計</b></td>
          <td><%= @order.payment_price %></td>
        </tr>
        <tr>
          <td><b>送料</b></td>
          <td><%= @order.shipping_cost %></td>
        </tr>
        <tr>
          <td><b>請求金額合計</b></td>
          <td><%= @order.shipping_cost + @order.payment_price %></td>
        </tr>
      </table>
    </div>
  </div>
</div>