config/routes.rb
Rails.application.routes.draw do
  
  # 顧客用
  # URL /customers/sign_in...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  namespace :public do
    root to: "homes#top"
    get "/about" => "homes#about", as: "about"
    post "/orders/confirm" => "orders#confirm"
    get "/orders/finish" => "orders#finish"
    resources :orders, only: [:new, :create, :index, :show]
    resources :items, only: [:index, :show]
    # resources :customers, only: [:show, :edit, :update]
    get "/customers/show" => "customers#show"
    get "/customers/show/eidt" => "customers#edit"
    patch "/customers/show" => "customers#update"
    get "/customers/check" => "customers#check"
    patch "/customers/withdraw" => "customers#withdraw"
    resources :cart_items, only: [:index, :create, :update]
    delete "/cart_items/destroy_all" => "cart_items#destroy_all"
    delete "/cart_items/:id" => "cart_items#destroy"
  end
  
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    # root to: "homes#top"
    get "/homes" => "homes#top"
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show]
  end
  
  get "/about" => "homes#about", as: "about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  def subtotal
    item.with_tax_price * amount
  end
  
  def total_price
    item.to_a.sum { |item| item.total_price }
  end

  def sum_of_price
    item.with_tax_price * amount
  end  
  
  validates :item_id, presence: true
  validates :customer_id, presence: true
  validates :amount, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items
  has_many :orders
  def full_name
    self.last_name + " " + self.first_name
  end
  
  def full_name_kana
    self.last_name_kana + " " + self.first_name_kana
  end
  
  def customer_status
    if is_deleted == true
      "退会"
    else
      "有効"
    end
  end
  
  def active_for_authentication?
    super && (is_deleted == false)
  end
  
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :cart_items, dependent: :destroy
  has_many :order_items
  def get_image(width, height)
     unless image.attached?
       file_path = Rails.root.join('app/assets/images/no_image.jpg')
       image.attach(io: File.open(file_path), filename: 'default=image.jpg', content_type: 'image/jpeg')
     end
     image.variant(resize_to_limit: [width,height]).processed
  end
  
  def add_tax_price
    (self.price * 1.10).round
  end
  
  def with_tax_price
    (price * 1.1).floor
  end
    
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  belongs_to :customer
  enum payment_method: { credit_card: 0, transfer: 1 }
  
  def address_display
  '〒' + current_customer.postal_code + ' ' + current_customer.address + ' ' + current_customer.last_name + ' ' + current_customer.first_name
  end
  
  SIPPING_COST = 800
  
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @customers = Customer.all
  end
  
  def show 
    @customer = Customer.find(params[:id])
    
  end
  
  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path
  end
  
  private
  
    def customer_params
      params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
    end
    
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @orders = Order.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def new
    @item = Item.new
  end
  
  def index
    
    @items = Item.page(params[:page])
  end
  
  def show
    @item = Item.find(params[:id])
  end
  
  def create
    item = Item.new(item_params)
    item.save
    redirect_to admin_item_path(item.id)
  end
  
  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end
  
  private
  
    def item_params
      params.require(:item).permit(:name, :introduction, :image, :price)
    end
  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  def show
    @order = Order.find(params[:id])
    @customer = @order.customer
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!, except: [:top, :about, :index, :show]
  protect_from_forgery with: :exception
  
  helper_method :current_cart
  
  def current_cart
    if session[:cart_id]
      @cart = Cart.find(session[:cart_id])
    else
      @cart = Cart.create
      session[:cart_id] = @cart.id
    end
  end
  
  def after_sign_in_path_for(resource)
    case resource
    when Customer
      root_path
    when Admin
      admin_homes_path
    end
  end
  
  def after_sign_out_path_for(resource)
    case resource
    when :customer
      public_root_path
    when :admin
      new_admin_session_path
    end
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container-fluid">
          <a class="navbar-brand p-3" href="/public">ながのCAKE</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                  aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              
            <% if admin_signed_in? %>
              <div class="header row p-3">
                <% if request.fullpath.include? "/admin" %>
                <li class="nav-item p-3">
                  <%= link_to "商品一覧", admin_items_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item p-3">
                  <%= link_to "会員一覧", admin_customers_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item p-3">
                  <%= link_to "注文履歴一覧", admin_homes_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item p-3">
                  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %>
                </li>
              </div>
            <% else %>
              <div class="header row px-3 py-4">
                <li class="nav-item p-3">
                  <%= link_to "マイページ", public_customers_show_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item p-3">
                  <%= link_to "商品一覧", public_items_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item p-3">
                  <%= link_to "カート", public_cart_items_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item p-3">
                  <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link text-dark' %>
                </li>
              </div>
            <% end %>
            <% elsif customer_signed_in? %>
              <div class="header row px-3 py-4">
                <li class="nav-item p-3">
                  <%= link_to "マイページ", public_customers_show_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item p-3">
                  <%= link_to "商品一覧", public_items_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item p-3">
                  <%= link_to "カート", public_cart_items_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item p-3">
                  <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link text-dark' %>
                </li>
              </div>
            <% else %>
              <div class="header row px-3 py-4">
                <li class="nav-item p-3">
                  <%= link_to "About", public_about_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item p-3">
                  <%= link_to "商品一覧", public_items_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item p-3">
                  <%= link_to "新規登録", new_customer_registration_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item p-3">
                  <%= link_to "ログイン", new_customer_session_path, class: 'nav-link text-dark' %>
                </li>
              </div>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>    
    </header>
    <%= yield %>
  </body>
</html>